/* Salone Lyrics — preview content.
   Artist facts are summarised from published sources (listed per artist). Artist photos are not used yet:
   until official photos or permission arrive, each artist shows a labelled Pexels stand-in (stand:true). Pexels images are used for illustrative (non-artist) imagery.
   Song lyrics are NOT reproduced: real songs show a "lyrics coming soon" panel until artists supply them. */

const HOT25 = "https://sierraloaded.sl/entertainment/full-list-20-hottest-artistes-sierra-leone-2025/";
window.SL_PHOTOS = {
  /* ---- Real artist photos (press / profile images) ---- */
  "r-drizilik": { page:"https://www.pexels.com/photo/smiling-man-singing-while-holding-his-black-hat-8043759/", by:"ANTONI SHKRABA production / Pexels", alt:"Singer tipping his hat at a vintage microphone", pos:"45% 25%", stand:true },
  "r-kao-denero": { page:"https://www.pexels.com/photo/black-man-posing-in-suit-17350030/", by:"Andy Coffie / Pexels", alt:"Performer in a blazer striking a pose", pos:"50% 20%", stand:true },
  "r-bakitenno": { page:"https://www.pexels.com/photo/man-in-black-hoodie-wearing-headphones-11975320/", by:"Emmanuel Jason Eliphalet / Pexels", alt:"Listener in headphones giving a thumbs up", pos:"50% 15%", stand:true },
  "r-apreel": { page:"https://www.pexels.com/photo/photo-of-woman-singing-in-music-studio-2531728/", by:"Papa Yaw / Pexels", alt:"Vocalist singing into a studio microphone", pos:"50% 25%", stand:true },
  "r-incredible-jj": { page:"https://www.pexels.com/photo/side-view-of-a-man-singing-while-holding-a-microphone-8043715/", by:"ANTONI SHKRABA production / Pexels", alt:"Singer performing into a vintage microphone", pos:"50% 20%", stand:true },
  "r-kracktwist": { page:"https://www.pexels.com/photo/casual-studio-portrait-of-a-man-in-black-30069255/", by:"josh_ dago__ / Pexels", alt:"Man in a bucket hat seated on a stool", pos:"50% 15%", stand:true },
  "r-boii": { page:"https://www.pexels.com/photo/man-playing-acoustic-guitar-20576428/", by:"Nduwa Siachaba / Pexels", alt:"Guitarist seated with an acoustic guitar", pos:"50% 20%", stand:true },
  "r-emmerson": { page:"https://www.pexels.com/photo/grayscale-photo-of-a-man-playing-trumpet-11662074/", by:"Alfo Medeiros / Pexels", alt:"Trumpeter playing into a microphone", pos:"50% 20%", stand:true },
  "r-laj": { page:"https://www.pexels.com/photo/a-man-playing-a-djembe-on-a-field-10433635/", by:"cottonbro studio / Pexels", alt:"Drummer holding a djembe", pos:"50% 15%", stand:true },
  "r-d4nny": { page:"https://www.pexels.com/photo/portrait-photo-of-smiling-woman-in-black-top-and-glasses-wearing-white-headphones-3765147/", by:"Andrea Piacquadio / Pexels", alt:"Listener with curly hair on white headphones", pos:"50% 30%", stand:true },
  "r-samza": { page:"https://www.pexels.com/photo/a-woman-holding-a-microphone-8043840/", by:"ANTONI SHKRABA production / Pexels", alt:"Singer laughing as she holds a microphone", pos:"45% 25%", stand:true },
  "r-itribe": { page:"https://www.pexels.com/photo/portrait-of-beautiful-african-woman-11440539/", by:"Ottun Abdulmalik / Pexels", alt:"Woman in a white head wrap and beads", pos:"50% 20%", stand:true },
  "r-star-zee": { page:"https://www.pexels.com/photo/black-man-posing-in-suit-17350030/", by:"Andy Coffie / Pexels", alt:"Performer in a blazer striking a pose", pos:"50% 20%", stand:true },
  "r-rozzy-sokota": { page:"https://www.pexels.com/photo/photo-of-woman-singing-in-music-studio-2531728/", by:"Papa Yaw / Pexels", alt:"Vocalist singing into a studio microphone", pos:"50% 25%", stand:true },
  /* ---- Team placeholder headshots (Pexels stock, NOT the real team members) ---- */
  "r-t-ansumana": { page:"https://www.pexels.com/photo/a-happy-man-smiling-7562185/", by:"VAZHNIK / Pexels", alt:"Placeholder headshot", pos:"50% 20%", placeholder:true },
  "r-t-alpha":    { page:"https://www.pexels.com/photo/close-up-photo-of-man-s-face-2743754/", by:"David Kwewum / Pexels", alt:"Placeholder headshot", pos:"50% 20%", placeholder:true },
  "r-t-michael":  { page:"https://www.pexels.com/photo/confident-african-male-in-red-shirt-portrait-30386124/", by:"Boko Shots / Pexels", alt:"Placeholder headshot", pos:"50% 8%", placeholder:true },
  "r-t-chernor":  { page:"https://www.pexels.com/photo/cheerful-young-black-man-smiling-at-camera-5984158/", by:"Dapo Abideen / Pexels", alt:"Placeholder headshot", pos:"50% 20%", placeholder:true },
  "r-t-ahmed":    { page:"https://www.pexels.com/photo/cheerful-black-man-on-gray-background-6999225/", by:"Monstera Production / Pexels", alt:"Placeholder headshot", pos:"50% 20%", placeholder:true },
  /* ---- Pexels illustrative photography (not artists) ---- */
  "hero-suit":         { page:"https://www.pexels.com/photo/black-man-posing-in-suit-17350030/", by:"Andy Coffie / Pexels", alt:"Performer in a blazer striking a pose", pos:"50% 20%" },
  "vocalist-studio":   { page:"https://www.pexels.com/photo/photo-of-woman-singing-in-music-studio-2531728/", by:"Papa Yaw / Pexels", alt:"Vocalist singing into a studio microphone", pos:"50% 25%" },
  "singer-hat":        { page:"https://www.pexels.com/photo/smiling-man-singing-while-holding-his-black-hat-8043759/", by:"ANTONI SHKRABA production / Pexels", alt:"Singer tipping his hat at a vintage microphone", pos:"45% 25%" },
  "headphones-hoodie": { page:"https://www.pexels.com/photo/man-in-black-hoodie-wearing-headphones-11975320/", by:"Emmanuel Jason Eliphalet / Pexels", alt:"Listener in headphones giving a thumbs up", pos:"50% 15%" },
  "headphones-glasses":{ page:"https://www.pexels.com/photo/portrait-photo-of-smiling-woman-in-black-top-and-glasses-wearing-white-headphones-3765147/", by:"Andrea Piacquadio / Pexels", alt:"Listener with curly hair on white headphones", pos:"50% 30%" },
  "singer-side":       { page:"https://www.pexels.com/photo/side-view-of-a-man-singing-while-holding-a-microphone-8043715/", by:"ANTONI SHKRABA production / Pexels", alt:"Singer performing into a vintage microphone", pos:"50% 20%" },
  "singer-red":        { page:"https://www.pexels.com/photo/a-woman-holding-a-microphone-8043840/", by:"ANTONI SHKRABA production / Pexels", alt:"Singer laughing as she holds a microphone", pos:"45% 25%" },
  "guitarist":         { page:"https://www.pexels.com/photo/man-playing-acoustic-guitar-20576428/", by:"Nduwa Siachaba / Pexels", alt:"Guitarist seated with an acoustic guitar", pos:"50% 20%" },
  "djembe":            { page:"https://www.pexels.com/photo/a-man-playing-a-djembe-on-a-field-10433635/", by:"cottonbro studio / Pexels", alt:"Drummer holding a djembe", pos:"50% 15%" },
  "seated-studio":     { page:"https://www.pexels.com/photo/casual-studio-portrait-of-a-man-in-black-30069255/", by:"josh_ dago__ / Pexels", alt:"Man in a bucket hat seated on a stool", pos:"50% 15%" },
  "trumpet":           { page:"https://www.pexels.com/photo/grayscale-photo-of-a-man-playing-trumpet-11662074/", by:"Alfo Medeiros / Pexels", alt:"Trumpeter playing into a microphone", pos:"50% 20%" },
  "headwrap":          { page:"https://www.pexels.com/photo/portrait-of-beautiful-african-woman-11440539/", by:"Ottun Abdulmalik / Pexels", alt:"Woman in a white head wrap and beads", pos:"50% 20%" }
};

window.SL = {
artists: [
  { slug:"drizilik", name:"Drizilik", photo:"r-drizilik", genre:"Afro hip-hop", town:"Freetown", since:2011, label:"Shukubly", hot:1,
    intro:"A Freetown rapper and singer who blends hip-hop and Afrobeats and raps mainly in Krio.",
    bio:["Drizilik, born Benjamin Menelik George in Freetown in 1994, began recording in 2011. His stage name joins “Driz”, a nod to Drake, with his middle name, Menelik. The single “Pop Collar” made him a household name in Sierra Leone.","His debut album Shukubly (2018) won Album of the Year at the 2019 National Entertainment Awards, where he also took Best Afro Hip Hop Artist, Male Artist of the Year and Best Live Performer. He headlined the Freetown Music Festival in 2019 and was nominated for the Listener’s Choice award at the 2021 MTV Africa Music Awards.","In 2022 he released “Ashobi” featuring Idris Elba on the 7Wallace imprint, followed by a 14-track album of the same name. Sierraloaded ranked him number one on its list of the 20 Hottest Artistes in Sierra Leone for 2025, and he has announced a new album, Audacity."],
    facts:[["Real name","Benjamin Menelik George"],["Active since","2011"],["Debut album","Shukubly (2018)"]],
    awards:["National Entertainment Awards 2019: Album of the Year, Best Afro Hip Hop Artist, Male Artist of the Year, Best Live Performer","Nominee, MTV Africa Music Awards Listener’s Choice (2021)","#1, Sierraloaded 20 Hottest Artistes 2025"],
    links:[["Audiomack","https://audiomack.com/drizilik"]],
    sources:["https://www.okayafrica.com/drizilik-ashobi-sierra-leone-interview/","https://www.musicinafrica.net/node/232180",HOT25,"https://sierraloaded.sl/entertainment/drizilik-release-new-album-audacity/"] },
  { slug:"kao-denero", name:"Kao Denero", photo:"r-kao-denero", genre:"Hip-hop", town:"Freetown", since:2003, label:"Black Leo Entertainment", hot:2,
    intro:"A veteran rapper and the founder of Black Leo Entertainment, active since his 2003 debut album.",
    bio:["Kao Denero, born Amara Dennis Turay in Lungi, released his debut album Black Leo 4 Life in 2003. Later albums include Stories From Freetown, King of Africa (2005) and Heroes.","He founded and leads Black Leo Entertainment, also known as Black Leo Records. Coverage describes his music as socially conscious, pairing street storytelling with hip-hop and African rhythms.","In 2021 he was appointed Sierra Leone’s Special Envoy on Entertainment. In January 2024 he and LAJ released “Peace” together. Sierraloaded ranked him number two in its 20 Hottest Artistes of 2025."],
    facts:[["Real name","Amara Dennis Turay"],["From","Lungi"],["Label","Black Leo Entertainment"]],
    awards:["SLMTV Music Award (2009)","Nominee, African Rapper of the Year, 256 HipHop Awards (2020)","Special Envoy on Entertainment (2021)","#2, Sierraloaded 20 Hottest Artistes 2025"],
    links:[["Audiomack","https://audiomack.com/kao-denero"]],
    sources:["https://last.fm/music/Kao+Denero/+wiki","https://awokonewspapersl.com/?p=157764","https://www.premiermedia-sl.com/?p=6942",HOT25] },
  { slug:"bakitenno", name:"Bakitenno", photo:"r-bakitenno", genre:"Afrobeats", town:"Freetown", since:2020, label:"New Wayv Music", hot:3, spotlight:true,
    intro:"A fast-rising Afrobeat artist from Freetown, signed to New Wayv Music.",
    bio:["Bakitenno is an Afrobeat artist from Freetown who joined New Wayv Music in June 2020, according to his Audiomack biography.","His 2025 single “Bismillah” passed 100,000 plays on Audiomack. Other singles include “Problem” with Samza (2024), “Online”, “Shot” and “On You” (2025), and “Janka Nabay”, “Light” with Uchee and “Scatter” (2026).","He has featured on songs by Samza, Kwame Q7, MC Caro and Kelvin SL. Sierraloaded ranked him number three in its 20 Hottest Artistes of 2025."],
    facts:[["Label","New Wayv Music"],["Breakout","“Bismillah” (2025)"],["Base","Freetown"]],
    awards:["#3, Sierraloaded 20 Hottest Artistes 2025"],
    links:[["Audiomack","https://audiomack.com/bakitenno"],["YouTube","https://www.youtube.com/channel/UC6gAMfk7z11PS-14yaJktrA"]],
    sources:["https://audiomack.com/bakitenno","https://awokonewspapersl.com/?p=148185","https://sierraloaded.sl/videos/bakitenno-bismillah/",HOT25] },
  { slug:"kracktwist", name:"Kracktwist", photo:"r-kracktwist", genre:"Hip-hop", town:"Lumley, Freetown", label:"Independent", hot:7,
    intro:"A Lumley rapper known for storytelling verses and social commentary.",
    bio:["Kracktwist, real name Ishmael Kamara, is a rapper from Lumley in Freetown. He signed with Kabaka Multimedia Entertainment in early 2017 and released “Thop” later that year. His second album launched at the Radisson Blu in Freetown in March 2019.","He is known for storytelling lyrics and social commentary and has often worked with Samza. The two reunited on “Mi Paddi” with Nigeria’s Chechii.","Recording as Kracktwist Lamina, he released the independent EP Republicans in May 2025, the EP Aunty Kadie in early 2026, and “Break” with Ghana’s Lyrical Joe in June 2026."],
    facts:[["Real name","Ishmael Kamara"],["From","Lumley, Freetown"],["Latest EP","Aunty Kadie (2026)"]],
    awards:["#7, Sierraloaded 20 Hottest Artistes 2025"],
    links:[],
    sources:["https://fambul.com/kracktwist","https://awokonewspapersl.com/?p=158399","https://sierraloaded.sl/music/kracktwist-lamina-break-lyrical-joe/",HOT25] },
  { slug:"boii", name:"Boii", photo:"r-boii", genre:"Afrobeats", town:"Freetown", since:2020, hot:8,
    intro:"A Freetown Afrobeats and Afro-fusion singer behind 2024’s most-streamed Sierra Leonean song.",
    bio:["Boii is an Afrobeats and Afro-fusion singer from Freetown. She began singing in church and at birthday parties, later performing in school talent shows and Salone Kids Got Talent.","Her releases include “Paper” (2021), “Credit Alert” and “Sangere” (2023), and “Love Na Scam” (2024). In 2025 she released the EP Money or Honey.","Awoko named her 2024 single “Feel Alright” the most-streamed Sierra Leonean song of that year, with about 3.5 million streams across YouTube, Audiomack and Spotify."],
    facts:[["Breakout","“Feel Alright” (2024)"],["Latest EP","Money or Honey (2025)"],["Base","Freetown"]],
    awards:["Most-streamed Sierra Leonean song of 2024 (Awoko ranking)","#8, Sierraloaded 20 Hottest Artistes 2025"],
    links:[],
    sources:["https://guardian.ng/life/music/boiiafrobeats-spark-from-sierra-leone/","https://awokonewspapersl.com/?p=139364",HOT25] },
  { slug:"emmerson", name:"Emmerson", photo:"r-emmerson", genre:"Afropop", town:"Freetown", since:2002, label:"Sugar Entertainment", hot:12,
    intro:"A veteran Afropop singer known for songs about governance and accountability.",
    bio:["Emmerson Amidu Bockarie, born on 23 December 1980, studied at Njala University before turning to music. He released his first single, “Yu Go See Am”, in 2002, and his debut album Borbor Bele in 2004.","He became known for political songs about corruption, tribalism and partisanship. His 2007 album 2 Fut Arata is widely credited with shaping that year’s election conversation.","Later albums include Rise (2012), Kokobeh (2013), Survivor (2016) and the Afrobeat album 9 Lives (2020). In 2022 he won Afrobeat Song and Afrobeat Artiste of the Year at the Global Music Awards."],
    facts:[["Real name","Emmerson Amidu Bockarie"],["Debut album","Borbor Bele (2004)"],["Label","Sugar Entertainment"]],
    awards:["Global Music Awards 2022: Afrobeat Song of the Year, Afrobeat Artiste of the Year","#12, Sierraloaded 20 Hottest Artistes 2025"],
    links:[],
    sources:["https://en.wikipedia.org/wiki/Emmerson_(musician)","https://www.musicinafrica.net/node/11822",HOT25] },
  { slug:"laj", name:"LAJ", aka:"King Boss LA", photo:"r-laj", genre:"Hip-hop", town:"Freetown", since:2009, label:"Red Flag Movement", hot:13,
    intro:"Freetown rapper and head of the Red Flag Movement, named Peace Ambassador in 2024.",
    bio:["LAJ, also known as King Boss LA, is a rapper from Freetown and the founder of the Red Flag Movement (RFM) label. He released his debut album, Money Na Bank, in 2009.","He is known for songs including “Freedom” with CatHouse, “Lollipop” and “Say No to Kush”. In January 2024 he and Kao Denero released “Peace”, closing a long camp rivalry, and in February 2024 he was appointed Peace Ambassador.","His 2023 song “Monalisa” with Zainab Sheriff passed 50,000 streams on Audiomack, and he released “Gangster Luv” in July 2025."],
    facts:[["Also known as","King Boss LA"],["Label","Red Flag Movement"],["Debut album","Money Na Bank (2009)"]],
    awards:["Appointed Peace Ambassador (2024)","#13 (as Boss LA), Sierraloaded 20 Hottest Artistes 2025"],
    links:[],
    sources:["https://musicinafrica.net/node/34816","https://www.premiermedia-sl.com/?p=15968","https://awokonewspapersl.com/king-boss-la-and-zainab-sheriffs-song-monalisa-surpasses-50000-streams-on-audiomack/",HOT25] },
  { slug:"apreel", name:"ApreeL", photo:"r-apreel", genre:"R&B", town:"Freetown", label:"Eminence Africa Entertainment", hot:15,
    intro:"An R&B and Afrobeat singer whose Audiomack catalogue has passed 5 million streams.",
    bio:["ApreeL, born Kabba Sesay, is an R&B artist signed to Eminence Africa Entertainment. His music mixes Afrobeat and Afro-soul with Krio.","In 2026 his Audiomack catalogue passed 5 million streams. “Control”, “Swity Miliki” and “O’Way” have each passed one million plays on the platform.","In August 2026 he released “Farr Away” with Liberian artist MC Caro, his first international collaboration. His motto: “Not coincidence but consistency.”"],
    facts:[["Real name","Kabba Sesay"],["Label","Eminence Africa Entertainment"],["Latest","“Farr Away” (2026)"]],
    awards:["5 million Audiomack streams (2026)","#15, Sierraloaded 20 Hottest Artistes 2025"],
    links:[["Audiomack","https://audiomack.com/apreel"],["YouTube","https://youtube.com/@boyapriil"],["TikTok","https://www.tiktok.com/@apriill_01"]],
    sources:["https://audiomack.com/apreel","https://awokonewspapersl.com/apreel-celebrates-5-million-audio-mack-streams-milestone/",HOT25] },
  { slug:"incredible-jj", name:"Incredible JJ", photo:"r-incredible-jj", genre:"Afrobeats", town:"Freetown", label:"Independent", hot:18,
    intro:"An independent Afrobeats and R&B singer whose 2026 single “Crush” passed one million streams.",
    bio:["Incredible JJ, born James Junior Kaisama, is a Freetown-based Afrobeats and R&B singer. He is independent; in June 2026 fact-checker DUBAWA confirmed that a reported record-label signing was false.","His single “Decide” passed 250,000 streams in its first month in early 2025 and sparked dance challenges on TikTok. In 2026 “Crush”, produced by Nashito Kulala, passed one million streams.","In May 2026 he held a listening party for his EP The Maths, which features LAJ."],
    facts:[["Real name","James Junior Kaisama"],["Latest EP","The Maths (2026)"],["Status","Independent"]],
    awards:["“Crush” passed 1 million streams (2026)","#18, Sierraloaded 20 Hottest Artistes 2025"],
    links:[],
    sources:["https://www.premiermedia-sl.com/?p=21038","https://dubawa.org/false-don-jazzy-has-not-signed-sierra-leonean-artist-incredible-jj-to-mavin-records/","https://awokonewspapersl.com/crushing-it-jjs-hit-tops-one-million-streams/",HOT25] },
  { slug:"d4nny", name:"D4nny", photo:"r-d4nny", genre:"Afropop", town:"Sierra Leone",
    intro:"A young producer, artist and songwriter working across Afrobeats, Afropop and dancehall.",
    bio:["D4nny is a Sierra Leonean producer, artist and songwriter whose sound mixes vocal melodies with contemporary electronic rhythms.","His songs include “Freak” featuring Drizilik, “Halle” and “Injure”. In 2026 he released “Akeh” featuring A6Milli.","Sierraloaded lists Drizilik’s “Audacity” as featuring D4nny Beatz."],
    facts:[["Roles","Producer, artist, songwriter"],["Latest","“Akeh” ft. A6Milli (2026)"]],
    awards:[], links:[],
    sources:["https://events.musicofourdesire.com/artist/d4nny","https://sierraloaded.sl/music/d4nny-akeh-a6milli/","https://sierraloaded.sl/music/drizilik-audacity-d4nny-beatz/"] },
  { slug:"samza", name:"Samza", photo:"r-samza", genre:"Hip-hop", town:"Freetown", hot:5,
    intro:"A rapper and frequent collaborator of Kracktwist and Bakitenno.",
    bio:["Samza is a Sierra Leonean rapper who has worked closely with Kracktwist over several years. The two reunited on “Mi Paddi” with Nigeria’s Chechii.","He features on Bakitenno’s 2024 single “Problem”. Sierraloaded ranked him number five in its 20 Hottest Artistes of 2025.","A full profile is in preparation with the artist’s team."],
    facts:[["Known for","“Mi Paddi”, “Problem”"]], awards:["#5, Sierraloaded 20 Hottest Artistes 2025"], links:[], partial:true,
    sources:["https://awokonewspapersl.com/krack-twist-samza-reunite-after-three-years-team-up-with-nigerias-chechii-on-new-single-mi-paddi/",HOT25] },
  { slug:"itribe", name:"I-Tribe", photo:"r-itribe", genre:"Afrobeats", town:"Freetown", hot:6,
    intro:"A singer whose collaborations span Kao Denero, Kracktwist and Swadu.",
    bio:["I-Tribe features on Kao Denero’s 2025 single “Like A Star” and on Swadu’s “It Is What It Is” alongside Kracktwist.","Sierraloaded ranked I-Tribe number six in its 20 Hottest Artistes of 2025.","A full profile is in preparation with the artist’s team."],
    facts:[["Known for","“Like A Star” with Kao Denero"]], awards:["#6, Sierraloaded 20 Hottest Artistes 2025"], links:[], partial:true,
    sources:["https://awokonewspapersl.com/?p=150756","https://sierraloaded.sl/music/swadu-it-is-what-it-is-itribe-kracktwist/",HOT25] },
  { slug:"star-zee", name:"Star Zee", photo:"r-star-zee", genre:"Hip-hop", town:"Freetown", hot:16,
    intro:"A rapper featured on the 2020 posse cut “Hustle Go Make Sense”.",
    bio:["Star Zee appears with Kracktwist, Arkman and Markmuday on “Hustle Go Make Sense” (2020).","Sierraloaded ranked Star Zee number sixteen in its 20 Hottest Artistes of 2025.","A full profile is in preparation with the artist’s team."],
    facts:[["Known for","“Hustle Go Make Sense” (2020)"]], awards:["#16, Sierraloaded 20 Hottest Artistes 2025"], links:[], partial:true,
    sources:["https://awokonewspapersl.com/?p=141908",HOT25] },
  { slug:"rozzy-sokota", name:"Rozzy Sokota", photo:"r-rozzy-sokota", genre:"R&B", town:"Freetown", label:"Sokota Vybe",
    intro:"A Freetown R&B and Afropop singer who records under her own Sokota Vybe name.",
    bio:["Rozzy Sokota makes R&B, Afropop and what she calls Afrosounds, recording under the Sokota Vybe name. She released an album titled SokotaVybe.","She has worked with I-Tribe, Markmuday, Blesz, Kracktwist, Samza and Arkman, including “Abandawa” with Arkman.","She has been named among the 50 Most Influential Sierra Leonean Women."],
    facts:[["Label","Sokota Vybe"],["Known for","“Abandawa” ft. Arkman"]], awards:["Named among the 50 Most Influential Sierra Leonean Women"],
    links:[["Audiomack","https://audiomack.com/rozzysokota"],["Instagram","https://www.instagram.com/rozzy_sokota"],["TikTok","https://www.tiktok.com/@rozzysokota"]],
    sources:["https://audiomack.com/rozzysokota","https://www.premiermedia-sl.com/?p=9191"] },
  { slug:"gemy", name:"Gemy", photo:null, genre:"To be confirmed", town:"Sierra Leone", pending:true,
    intro:"Profile in progress. Salone Lyrics is confirming details with the artist’s team.",
    bio:["We could not yet verify Gemy’s biography, releases or official links from published sources.","This profile will be completed once the artist or their management supplies official details and photos."],
    facts:[], awards:[], links:[], sources:[] },
  { slug:"demo", name:"Salone Lyrics", photo:null, genre:"Demo", town:"", hidden:true, intro:"", bio:[], facts:[], awards:[], links:[], sources:[] }
],

songs: [
  /* Lyric reader demo (original sample text, not a real song) */
  { slug:"lyric-reader-demo", title:"Mama Salone", artist:"demo", genre:"Demo", type:"Demo", year:2026, demo:true,
    credits:{ "Text":"Original sample written for this preview" },
    lyrics:[
      ["Verse 1",["Early morning, kettle on the coal","Mama humming songs I never told","She say pikin, hold your head up high","Salone sun go dry the tears you cry"]],
      ["Chorus",["Mama Salone, Mama Salone","Every road I walk, it lead me home","Mama Salone, you never leave me alone","Mama Salone"]],
      ["Verse 2",["Market voices calling down the street","Pepper, fish and dust upon my feet","Far away I keep your picture near","Close my eyes and you are standing here"]],
      ["Bridge",["Tenki, tenki for the hands that hold","Tenki for the stories that you told"]]
    ],
    translation:{ label:"English (example translation)", note:"Krio lines translated for readers outside Sierra Leone.", lines:{ "She say pikin, hold your head up high":"She says, child, hold your head up high", "Salone sun go dry the tears you cry":"The Salone sun will dry the tears you cry", "Tenki, tenki for the hands that hold":"Thank you, thank you for the hands that hold", "Tenki for the stories that you told":"Thank you for the stories that you told" } } },
  /* Real songs: titles and credits from published sources. Lyrics pending artist approval. */
  { slug:"ashobi", title:"Ashobi", artist:"drizilik", feat:"Idris Elba", genre:"Afro hip-hop", type:"Single", year:2022, release:"ashobi-album", label:"7Wallace" },
  { slug:"pop-collar", title:"Pop Collar", artist:"drizilik", genre:"Afro hip-hop", type:"Single", year:null },
  { slug:"move-right", title:"Move Right", artist:"drizilik", feat:"Big Zuu", genre:"Afro hip-hop", type:"Single", year:2020 },
  { slug:"popular", title:"Popular", artist:"drizilik", feat:"Ramoni", genre:"Afro hip-hop", type:"Single", year:2022 },
  { slug:"fana-makit", title:"Fana Makit", artist:"drizilik", genre:"Afro hip-hop", type:"Album", year:2022, release:"ashobi-album" },
  { slug:"audacity", title:"Audacity", artist:"drizilik", featA:"d4nny", feat:"D4nny Beatz", genre:"Afro hip-hop", type:"Single", year:2026 },
  { slug:"peace", title:"Peace", artist:"kao-denero", featA:"laj", feat:"LAJ", genre:"Hip-hop", type:"Single", year:2024 },
  { slug:"emonah", title:"Emonah", artist:"kao-denero", feat:"Big Joe", genre:"Hip-hop", type:"Single", year:null },
  { slug:"like-a-star", title:"Like A Star", artist:"kao-denero", featA:"itribe", feat:"I-Tribe", genre:"Hip-hop", type:"Single", year:2025 },
  { slug:"bismillah", title:"Bismillah", artist:"bakitenno", genre:"Afrobeats", type:"Single", year:2025 },
  { slug:"problem", title:"Problem", artist:"bakitenno", featA:"samza", feat:"Samza", genre:"Afrobeats", type:"Single", year:2024 },
  { slug:"janka-nabay", title:"Janka Nabay", artist:"bakitenno", genre:"Afrobeats", type:"Single", year:2026 },
  { slug:"light", title:"Light", artist:"bakitenno", feat:"Uchee", genre:"Afrobeats", type:"Single", year:2026 },
  { slug:"break", title:"Break", artist:"kracktwist", feat:"Lyrical Joe", genre:"Hip-hop", type:"Single", year:2026 },
  { slug:"mi-paddi", title:"Mi Paddi", artist:"kracktwist", featA:"samza", feat:"Samza, Chechii", genre:"Hip-hop", type:"Single", year:null },
  { slug:"hustle-go-make-sense", title:"Hustle Go Make Sense", artist:"kracktwist", featA:"star-zee", feat:"Star Zee, Arkman, Markmuday", genre:"Hip-hop", type:"Single", year:2020 },
  { slug:"thop", title:"Thop", artist:"kracktwist", genre:"Hip-hop", type:"Single", year:2017 },
  { slug:"feel-alright", title:"Feel Alright", artist:"boii", genre:"Afrobeats", type:"Single", year:2024 },
  { slug:"love-na-scam", title:"Love Na Scam", artist:"boii", genre:"Afrobeats", type:"Single", year:2024 },
  { slug:"sangere", title:"Sangere", artist:"boii", genre:"Afrobeats", type:"Single", year:2023 },
  { slug:"credit-alert", title:"Credit Alert", artist:"boii", genre:"Afrobeats", type:"Single", year:2023 },
  { slug:"yu-go-see-am", title:"Yu Go See Am", artist:"emmerson", genre:"Afropop", type:"Single", year:2002 },
  { slug:"borbor-bele", title:"Borbor Bele", artist:"emmerson", genre:"Afropop", type:"Album", year:2004, release:"borbor-bele" },
  { slug:"kokonat-ed", title:"Kokonat Ed", artist:"emmerson", genre:"Afrobeats", type:"Album", year:2020, release:"9-lives" },
  { slug:"fun", title:"FUN", artist:"emmerson", genre:"Afropop", type:"Single", year:2023 },
  { slug:"monalisa", title:"Monalisa", artist:"laj", feat:"Zainab Sheriff", genre:"Hip-hop", type:"Single", year:2023 },
  { slug:"gangster-luv", title:"Gangster Luv", artist:"laj", genre:"Hip-hop", type:"Single", year:2025 },
  { slug:"freedom", title:"Freedom", artist:"laj", feat:"CatHouse", genre:"Hip-hop", type:"Single", year:null },
  { slug:"say-no-to-kush", title:"Say No to Kush", artist:"laj", genre:"Hip-hop", type:"Single", year:null },
  { slug:"control", title:"Control", artist:"apreel", genre:"R&B", type:"Single", year:null },
  { slug:"swity-miliki", title:"Swity Miliki", artist:"apreel", genre:"R&B", type:"Single", year:null },
  { slug:"o-way", title:"O’Way", artist:"apreel", genre:"R&B", type:"Single", year:null },
  { slug:"farr-away", title:"Farr Away", artist:"apreel", feat:"MC Caro", genre:"R&B", type:"Single", year:2026 },
  { slug:"crush", title:"Crush", artist:"incredible-jj", genre:"Afrobeats", type:"Single", year:2026, credits:{ "Produced by":"Nashito Kulala" } },
  { slug:"decide", title:"Decide", artist:"incredible-jj", genre:"Afrobeats", type:"Single", year:2025 },
  { slug:"freak", title:"Freak", artist:"d4nny", featA:"drizilik", feat:"Drizilik", genre:"Afropop", type:"Single", year:null },
  { slug:"akeh", title:"Akeh", artist:"d4nny", feat:"A6Milli", genre:"Afropop", type:"Single", year:2026 },
  { slug:"abandawa", title:"Abandawa", artist:"rozzy-sokota", feat:"Arkman", genre:"R&B", type:"Single", year:null }
],

releases: [
  { slug:"audacity-album", title:"Audacity", artist:"drizilik", type:"Album", year:2026, note:"Announced", tracks:["audacity"], colour:"charcoal" },
  { slug:"the-maths", title:"The Maths", artist:"incredible-jj", type:"EP", year:2026, tracks:[], colour:"amber" },
  { slug:"aunty-kadie", title:"Aunty Kadie", artist:"kracktwist", type:"EP", year:2026, tracks:[], colour:"green" },
  { slug:"money-or-honey", title:"Money or Honey", artist:"boii", type:"EP", year:2025, tracks:[], colour:"blue" },
  { slug:"republicans", title:"Republicans", artist:"kracktwist", type:"EP", year:2025, tracks:[], colour:"charcoal" },
  { slug:"ashobi-album", title:"Ashobi", artist:"drizilik", type:"Album", year:2022, tracks:["ashobi","fana-makit"], colour:"green" },
  { slug:"9-lives", title:"9 Lives", artist:"emmerson", type:"Album", year:2020, tracks:["kokonat-ed"], colour:"amber" },
  { slug:"shukubly", title:"Shukubly", artist:"drizilik", type:"Album", year:2018, tracks:[], colour:"blue" },
  { slug:"money-na-bank", title:"Money Na Bank", artist:"laj", type:"Album", year:2009, tracks:[], colour:"charcoal" },
  { slug:"borbor-bele", title:"Borbor Bele", artist:"emmerson", type:"Album", year:2004, tracks:["borbor-bele"], colour:"green" },
  { slug:"black-leo-4-life", title:"Black Leo 4 Life", artist:"kao-denero", type:"Album", year:2003, tracks:[], colour:"blue" }
],

picks: ["crush","feel-alright","bismillah","ashobi","peace","farr-away","break","fun"],

articles: [
  { slug:"hottest-2025", cat:"Industry", title:"Drizilik tops Sierraloaded’s 20 Hottest Artistes of 2025", date:"2026-01-08", author:"writer-1", photo:"r-drizilik", artist:"drizilik", songs:["ashobi","audacity"], related:["kao-denero","bakitenno","kracktwist","boii"],
    summary:"Drizilik, Kao Denero and Bakitenno lead the list, with Kracktwist, Boii, Emmerson, LAJ, ApreeL and Incredible JJ all in the top 20.",
    body:["Sierraloaded’s annual ranking of the 20 Hottest Artistes in Sierra Leone put Drizilik at number one for 2025, followed by Kao Denero and Bakitenno.","The top ten also included Famous, Samza, I-Tribe, Kracktwist, Boii, Mascot and Legacy Boy. Emmerson came in at 12, Boss LA at 13, ApreeL at 15, Star Zee at 16 and Incredible JJ at 18.","The list mixes veterans who have shaped Salone music for two decades with artists whose careers have grown through Audiomack and TikTok in the past few years."],
    sources:[HOT25] },
  { slug:"crush-one-million", cat:"Releases", title:"Incredible JJ’s “Crush” passes one million streams", date:"2026-06-20", author:"writer-2", photo:"r-incredible-jj", artist:"incredible-jj", songs:["crush","decide"], related:["laj"],
    summary:"The independent singer’s single, produced by Nashito Kulala, crossed the mark across platforms.",
    body:["Incredible JJ’s single “Crush” has passed one million streams across platforms, according to Awoko. The song was produced by Nashito Kulala, and its music video premiered the same day the milestone was announced.","The milestone follows “Decide”, which passed 250,000 streams in its first month in early 2025 and started dance challenges on TikTok.","In May 2026 he hosted a listening party for his EP The Maths, which features LAJ."],
    sources:["https://awokonewspapersl.com/crushing-it-jjs-hit-tops-one-million-streams/","https://awokonewspapersl.com/music-stars-light-up-incredible-jjs-explosive-the-maths-ep-listening-party/"] },
  { slug:"peace-kao-laj", cat:"Culture", title:"Kao Denero and LAJ: from rival camps to “Peace”", date:"2026-02-12", author:"writer-1", photo:"r-kao-denero", artist:"kao-denero", songs:["peace","like-a-star","monalisa"], related:["laj"],
    summary:"How two of Freetown’s biggest rap camps came together on one record.",
    body:["For years the rivalry between Kao Denero’s Black Leo camp and LAJ’s Red Flag Movement shaped Sierra Leonean hip-hop, and the press compared it to America’s East Coast and West Coast feud.","In January 2024 the two rappers released “Peace” together. In February 2024 LAJ was appointed Peace Ambassador.","Kao Denero, who was named Special Envoy on Entertainment in 2021, continues to release music through Black Leo Entertainment."],
    sources:["https://manoreporters.com/news/politics/sierra-leone-popular-rapper-laj-leaves-prison-like-a-king-calls-for-unity","https://awokonewspapersl.com/?p=157764"] },
  { slug:"apreel-5-million", cat:"Industry", title:"ApreeL passes 5 million Audiomack streams", date:"2026-07-15", author:"writer-3", photo:"r-apreel", artist:"apreel", songs:["control","swity-miliki","o-way","farr-away"], related:["bakitenno"],
    summary:"Three of his singles have each crossed one million plays on the platform.",
    body:["ApreeL’s Audiomack catalogue has passed 5 million total streams. “Control”, “Swity Miliki” and “O’Way” have each passed one million plays.","The Eminence Africa Entertainment singer released “Farr Away” with Liberian artist MC Caro in August 2026, his first international collaboration."],
    sources:["https://awokonewspapersl.com/apreel-celebrates-5-million-audio-mack-streams-milestone/","https://awokonewspapersl.com/?p=160887"] },
  { slug:"break-lyrical-joe", cat:"Releases", title:"Kracktwist Lamina links with Ghana’s Lyrical Joe on “Break”", date:"2026-06-28", author:"writer-2", photo:"r-kracktwist", artist:"kracktwist", songs:["break","mi-paddi","hustle-go-make-sense"], related:["samza","star-zee"],
    summary:"The Lumley rapper’s new single follows his EPs Republicans and Aunty Kadie.",
    body:["Kracktwist, now recording as Kracktwist Lamina, released “Break” featuring Ghanaian rapper Lyrical Joe in June 2026. Lamzo Jay produced the track.","It follows the independent EP Republicans (May 2025) and Aunty Kadie (early 2026)."],
    sources:["https://sierraloaded.sl/music/kracktwist-lamina-break-lyrical-joe/","https://awokonewspapersl.com/?p=158399"] },
  { slug:"feel-alright-2024", cat:"Industry", title:"Boii’s “Feel Alright” was 2024’s most-streamed Salone song", date:"2026-03-04", author:"writer-3", photo:"r-boii", artist:"boii", songs:["feel-alright","love-na-scam","sangere"], related:[],
    summary:"About 3.5 million streams across YouTube, Audiomack and Spotify, according to Awoko.",
    body:["Awoko named Boii’s “Feel Alright” the most-streamed Sierra Leonean song of 2024, with about 3.52 million streams across YouTube, Audiomack and Spotify.","The Freetown singer followed it with the EP Money or Honey in 2025."],
    sources:["https://awokonewspapersl.com/?p=139364"] },
  { slug:"emmerson-two-decades", cat:"Culture", title:"Emmerson: two decades of songs about governance", date:"2026-04-18", author:"writer-1", photo:"r-emmerson", artist:"emmerson", songs:["yu-go-see-am","borbor-bele","kokonat-ed","fun"], related:[],
    summary:"From “Yu Go See Am” to 9 Lives, a look at Sierra Leone’s most political pop catalogue.",
    body:["Emmerson Bockarie released his first single, “Yu Go See Am”, in 2002 and his debut album, Borbor Bele, in 2004.","His songs about corruption, tribalism and partisanship made him one of Sierra Leone’s most discussed artists, and his 2007 album 2 Fut Arata is widely credited with shaping that year’s election conversation.","After returning to Sierra Leone in 2020 he released the Afrobeat album 9 Lives, which includes “Kokonat Ed”."],
    sources:["https://en.wikipedia.org/wiki/Emmerson_(musician)","https://sierraloaded.sl/opinion/emerson-bockarie-governance-accountability/"] }
  ,{ slug:"submit-lyrics-guide", sample:true, cat:"Guides", title:"How to get your lyrics on Salone Lyrics", date:"2026-10-05", author:"writer-2", photo:"headphones-glasses", artist:null, songs:["lyric-reader-demo"], related:[],
    summary:"A step-by-step guide for artists and managers who want their words published correctly.",
    body:["Start by gathering the final lyrics exactly as they are sung, including repeated choruses and ad-libs that matter to the song.","Add the full credits: writers, producers, featured artists and the release date. Editors check these against your official listings.","Send everything through the lyrics form on your song page, or ask for a profile through Promote With Us. Our team confirms the details with you before anything goes live.","Once published, fans can quote your words correctly in captions, covers and videos."],
    sources:[] }
  ,{ slug:"tiktok-growth-tips", sample:true, cat:"Guides", title:"Five ways Salone artists can grow on TikTok", date:"2026-10-02", author:"writer-3", photo:"headphones-hoodie", artist:null, songs:[], related:["bakitenno","incredible-jj"],
    summary:"Short clips, clear hooks and consistent posting: a practical checklist for new releases.",
    body:["Pick the 15 seconds of your song that people will want to sing back, and build every clip around it.","Post before release day so fans already know the hook when the full song arrives.","Invite dancers and creators to try a simple move or a lyric challenge, and repost the best ones.","Keep your profile links up to date so listeners can find the full song in one tap.","Post consistently for the first four weeks after a release, when interest is highest."],
    sources:[] }
  ,{ slug:"studio-day-feature", sample:true, cat:"Features", title:"A day inside a Freetown studio session", date:"2026-09-28", author:"writer-1", photo:"vocalist-studio", artist:null, songs:[], related:[],
    summary:"From the first beat to the final take: what a typical recording day looks like.",
    body:["The session starts late morning, when the producer loads the beat and the artist runs through the hook a few times.","Verses are recorded in short passes, with the engineer marking the strongest lines for the final comp.","By evening the team listens back on phone speakers, because that is how most fans will hear the song first.","This is a sample feature written to show how long-form stories appear on the site."],
    sources:[] }
  ,{ slug:"krio-in-music", sample:true, cat:"Features", title:"Why Krio lyrics travel so well", date:"2026-09-21", author:"writer-1", photo:"singer-side", artist:null, songs:[], related:["drizilik","kracktwist"],
    summary:"Everyday expressions give Salone songs a sound fans at home and abroad recognise instantly.",
    body:["Krio lines carry humour, proverbs and street talk that listeners repeat long after the song ends.","For fans in the diaspora, a familiar phrase can feel like a message from home.","Translations on Salone Lyrics help new listeners follow along without losing the original words.","This is a sample feature written to show how culture stories appear on the site."],
    sources:[] }
  ,{ slug:"live-show-checklist", sample:true, cat:"Guides", title:"A checklist for your first headline show", date:"2026-09-14", author:"writer-3", photo:"singer-hat", artist:null, songs:[], related:[],
    summary:"Venue, sound check, set list and promotion: what to confirm before the big night.",
    body:["Confirm the venue, capacity and ticket price in writing at least four weeks ahead.","Book a proper sound check and bring your own backing tracks on two separate devices.","Plan a set list that opens strong, saves the biggest song for last and leaves room for an encore.","List the show on Salone Lyrics Events so fans can add it to their calendars."],
    sources:[] }
  ,{ slug:"playlist-pitching", sample:true, cat:"Guides", title:"Pitching your song to playlists: a simple plan", date:"2026-09-07", author:"writer-2", photo:"trumpet", artist:null, songs:[], related:[],
    summary:"Timing, a short pitch and accurate metadata make the biggest difference.",
    body:["Upload your release to your distributor at least three weeks early so you can pitch it before release day.","Write a short pitch: genre, mood, the story behind the song and any notable collaborators.","Make sure your credits and lyrics are correct everywhere, including on Salone Lyrics.","This is a sample guide written to show how advice articles appear on the site."],
    sources:[] }

],

events: [
  { slug:"salone-lyrics-live", title:"Salone Lyrics Live", date:"2026-10-10", time:"17:00", end:"22:00", venue:"Venue to be confirmed", address:"Freetown", town:"Freetown", type:"Concert", paid:true, price:"Ticket details to be announced", status:"upcoming", lineup:"Lineup to be announced", organiser:"Salone Lyrics (sample listing)",
    desc:"A sample listing showing how concerts appear on the site. Real events will show confirmed performers, ticket links and venue details." },
  { slug:"lyric-writing-workshop", title:"Lyric Writing Workshop", date:"2026-10-11", time:"14:00", end:"17:00", venue:"Venue to be confirmed", address:"Bo", town:"Bo", type:"Workshop", paid:false, price:"Free entry", status:"upcoming", lineup:"Facilitators to be announced", organiser:"Salone Lyrics (sample listing)",
    desc:"A sample free event: a hands-on session on writing, checking and crediting lyrics." },
  { slug:"ep-listening-session", title:"EP Listening Session", date:"2026-10-17", time:"20:00", end:"23:00", venue:"Venue to be confirmed", address:"Freetown", town:"Freetown", type:"Listening session", paid:true, price:"Ticket details to be announced", status:"sold-out", lineup:"Artist to be announced", organiser:"Sample organiser",
    desc:"A sample listing showing the sold-out state." },
  { slug:"acoustic-evening", title:"Acoustic Evening", date:"2026-10-24", time:"18:30", end:"21:30", venue:"Venue to be confirmed", address:"Kenema", town:"Kenema", type:"Acoustic", paid:true, price:"Ticket details to be announced", status:"postponed", newDate:"New date to be announced", lineup:"Lineup to be announced", organiser:"Sample organiser",
    desc:"A sample listing showing the postponed state." },
  { slug:"street-cypher", title:"Street Cypher Night", date:"2026-10-31", time:"19:00", end:"23:30", venue:"Venue to be confirmed", address:"Makeni", town:"Makeni", type:"Concert", paid:true, price:"Ticket details to be announced", status:"cancelled", lineup:"Lineup to be announced", organiser:"Sample organiser",
    desc:"A sample listing showing the cancelled state." },
  { slug:"december-homecoming", title:"December Homecoming Concert", date:"2026-12-26", time:"16:00", end:"23:59", venue:"Venue to be confirmed", address:"Freetown", town:"Freetown", type:"Festival", paid:true, price:"Ticket details to be announced", status:"upcoming", lineup:"Lineup to be announced", organiser:"Salone Lyrics (sample listing)",
    desc:"A sample holiday concert listing for fans at home and visiting from the diaspora." },
  { slug:"launch-meetup", title:"Salone Lyrics Website Launch Meetup", date:"2026-09-20", time:"19:00", end:"21:00", venue:"Venue to be confirmed", address:"Freetown", town:"Freetown", type:"Meetup", paid:false, price:"Free entry", status:"completed", lineup:"Salone Lyrics team", organiser:"Salone Lyrics (sample listing)",
    desc:"A sample past event." }
],

videos: [
  { slug:"ashobi-video", title:"Ashobi", artist:"drizilik", kind:"Music video", orient:"landscape", photo:"r-drizilik" },
  { slug:"crush-video", title:"Crush", artist:"incredible-jj", kind:"Music video", orient:"landscape", photo:"r-incredible-jj" },
  { slug:"bismillah-video", title:"Bismillah", artist:"bakitenno", kind:"Music video", orient:"portrait", photo:"r-bakitenno" },
  { slug:"feel-alright-video", title:"Feel Alright", artist:"boii", kind:"Music video", orient:"landscape", photo:"r-boii" },
  { slug:"peace-video", title:"Peace", artist:"kao-denero", kind:"Music video", orient:"landscape", photo:"r-kao-denero" },
  { slug:"break-video", title:"Break", artist:"kracktwist", kind:"Music video", orient:"portrait", photo:"r-kracktwist" }
],

gallery: [
  { slug:"hottest-2025", title:"Salone’s hottest, 2025", items:["r-drizilik","r-kao-denero","r-bakitenno","r-samza","r-itribe","r-kracktwist","r-boii","r-emmerson"] },
  { slug:"more-artists", title:"More artists", items:["r-laj","r-apreel","r-star-zee","r-incredible-jj","r-d4nny"] },
  { slug:"studio-and-stage", title:"Studio and stage (illustrative)", items:["vocalist-studio","singer-hat","singer-side","trumpet"] }
],

team: [
  { name:"Ansumana Ngobeh", photo:"r-t-ansumana", role:"Lead Creator", bio:"Founder of Salone Lyrics. Leads editorial direction, artist relations and the platform’s growth across Facebook, Instagram and TikTok." },
  { name:"Alpha Fofanah", photo:"r-t-alpha", role:"Co-Creator", bio:"Co-runs the platform, shaping content plans, partnerships and community engagement." },
  { name:"Michael Nabieu", photo:"r-t-michael", role:"Graphic Designer", bio:"Designs lyric cards, artist features and campaign visuals." },
  { name:"Chernor M. Kamara", photo:"r-t-chernor", role:"Video Editor", bio:"Edits lyric videos, interviews and short-form content." },
  { name:"Ahmed S. Koroma", photo:"r-t-ahmed", role:"Video Editor", bio:"Edits lyric videos, performance clips and social cut-downs." },
  { id:"writer-1", name:"Article writer", sampleName:"Writer One", role:"Writer · Position open", open:true, bio:"Covers interviews, culture and long-form features." },
  { id:"writer-2", name:"Article writer", sampleName:"Writer Two", role:"Writer · Position open", open:true, bio:"Covers new releases and music news." },
  { id:"writer-3", name:"Article writer", sampleName:"Writer Three", role:"Writer · Position open", open:true, bio:"Covers the music business, streaming and industry." }
],

services: [
  { id:"profile", name:"Artist Profile", tag:"Your story, told right", photo:"vocalist-studio", what:"A written profile page with biography, music, videos and events, listed in the artist directory.", gets:["Edited biography","Profile page with music, video and event tabs","Directory listing"], duration:"Ongoing listing" },
  { id:"release", name:"Featured Release", tag:"New music, front and centre", photo:"headphones-hoodie", what:"Your single, EP or album highlighted in Latest Releases with a dedicated lyrics page.", gets:["Release page with tracklist and credits","Latest Releases placement","Lyrics page for one track"], duration:"Agreed with the team" },
  { id:"spotlight", name:"Weekly Spotlight", tag:"One week on the homepage", photo:"singer-red", what:"The homepage feature with a large portrait, introduction and links to your music.", gets:["Homepage Weekly Spotlight","Short interview or introduction","Announcement post on social media"], duration:"One week" },
  { id:"event", name:"Event Promotion", tag:"Fill the room", photo:"singer-side", what:"Your show listed and highlighted across the Events section, with add-to-calendar for fans.", gets:["Event page with ticket link","Homepage event row","Add-to-calendar"], duration:"Until the event date" },
  { id:"social", name:"Social Media Promotion", tag:"Lyric cards and short videos", photo:"headphones-glasses", what:"Lyric cards and short videos on Salone Lyrics Instagram and TikTok.", gets:["Lyric or feature post","Short video edit","Caption and tagging"], duration:"Agreed with the team" },
  { id:"banner", name:"Banner Placement", tag:"Seen, never in the lyrics", photo:"trumpet", what:"A clearly labelled banner placed outside reading areas.", gets:["Banner design check","Placement outside lyric text","Link to your page or tickets"], duration:"Agreed with the team" },
  { id:"combined", name:"Combined Campaign", tag:"Launch everything together", photo:"singer-hat", what:"A planned mix of website and social placements for a release or tour.", gets:["Campaign plan","Website and social placements","Wrap-up summary"], duration:"Agreed per campaign" }
]
};
